# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test Lib

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Setup & Test Lib
      run: |
        pdm install
        pdm add --group all
        python test/testlib.py